version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DATABASE_HOST: "mongodb://mongo:2717/"
      DATABASE_NAME: Games
      DATABASE_USER: savyab
      DATABASE_PASSWORD: megan2002
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    ports:
      - "2717:2717"
    environment:
      MONGO_INITDB_ROOT_USERNAME: savya
      MONGO_INITDB_ROOT_PASSWORD: megan

networks:
  default:
    external:
      name: my_network